project_name = "simglobe_analysis"

input_var = [
  "interest_rate",
  "vat_rate",
  "corporate_tax",
  "government_expenditure",
  "import_tariff"
]

output_var = [
  'real_gdp_growth',
  'inflation',
  'unemployment',
  'budget_balance',
  'approval_index', 
]

scenario = [
  "constant",
  "random"
]

unique = [
  "country",
  "period",
  "scenario"
]

trim_radius = 0.05





